name: face_recognition_app
description: A stylish Flutter app for face recognition with white, black, and blue theme.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  camera: ^0.10.5+5
  permission_handler: ^11.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image: ^4.1.3
  tflite_flutter: ^0.11.0
  google_mlkit_face_detection: ^0.13.1
  google_mlkit_commons: ^0.11.0
  qr_code_scanner_plus: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/models/
    - assets/models/FaceMobileNet_Float32.tflite